version: 2.1

orbs:
  aws-s3: circleci/aws-s3@2.0.0
  
jobs:
  deploy:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "./package.json" }}
            - v1-dependencies-
      - run:
          name: Install, test, and build
          command: |
            npm install
            npm run test
            npm run build
      - save_cache:
          key: dependency-cache-{{ checksum "./package.json" }}
          paths:
            - ./node_modules

      # deploy
      - aws-s3/sync:
          from: ./build
          to: 's3://bandcamp-merch-availability'
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
          arguments: |
            --acl public-read

workflows:
  version: 2

  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
