name: build

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "16"
    - name: Install dependencies
      run: |
        npm ci
    - name: Lint and Test
      run: |
        npm test
    - name: Build
      run: |
        npm run build
    - name: Store build results
      uses: actions/upload-artifact@v3
      with:
        name: build-results
        path: build/
        retention-days: 1

  upload-build-results:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create folder for synching
      run: |
        mkdir -p tmp
    - uses: actions/download-artifact@v3
      with:
        name: build-results
        path: tmp/
    - name: Upload build results to s3 bucket
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: "tmp"
